
//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: mikestart.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_mikestart_H__
#define __WDR_mikestart_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "mikestart_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_RADIOBOX_DEFAULTS = 10000;
const int ID_TEXT = 10001;
const int ID_TEXT_NAME = 10002;
const int ID_BUTTON_ES = 10003;
const int ID_BUTTON_ER = 10004;
const int ID_BUTTON_SS = 10005;
const int ID_BUTTON_EXTERNAL_PROCESSES = 10006;
const int ID_BUTTON_NC = 10007;
const int ID_BUTTON_LATTICE_GAS = 10008;
wxSizer *BasicSettings( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_NOTEBOOK = 10009;
wxSizer *Edit_Settings( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int STRENGTH_DISTRI = 10010;
const int GSP = 10011;
const int RATE_DISTRI = 10012;
const int GRP = 10013;
const int SPRING_DISTRI = 10014;
const int GSpP = 10015;
const int YOUNG_DISTRI = 10016;
const int EDIT_GAUSSIAN_YOUNG = 10017;
wxSizer *Distribution( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int CHECK_TIMESTEP = 10018;
const int TIMESTEP = 10019;
const int TS_DEF = 10020;
const int CHECK_MULT_RELAX = 10021;
const int MULT_RELAX = 10022;
const int RT_DEF = 10023;
wxSizer *Var_Edit_Set( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_BUTTON_SET_DEFAULT = 10024;
wxSizer *NB_Set( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int CHECK_SET_WALLS = 10025;
const int EDIT_WALLS = 10026;
const int CHECK_WEAKEN_HORIZ = 10027;
const int WEAKEN_HORIZ = 10028;
const int CHECK_WEAKEN_ALL = 10029;
const int WEAKEN_ALL = 10030;
const int ID_CHECKBOX_WEAKEN_GRAIN = 10031;
const int ID_BUTTON_WEAKEN_GRAIN = 10032;
const int ID_SPINCTRL_WEAKEN_GRAIN = 10033;
const int CHECK_MAKE_GB = 10034;
const int EDIT_GB = 10035;
wxSizer *Lattice( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_MINERAL = 10036;
const int ID_CHECKBOX_TRANSITION = 10037;
const int ID_CHECKBOX_TRANSITION_HEAT = 10038;
const int ID_TEXTCTRL_ACTIVATION_ENERGY = 10039;
const int ID_TEXTCTRL_START_GPA = 10040;
const int ID_CHECKBOX_HEAT_CONDUCTION = 10041;
const int ID_SPINCTRL_HEAT_CONDUCTION_NB = 10042;
const int ID_SPINCTRL_HEAT_CONDUCTION_T = 10043;
wxSizer *Minerals( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int CHECK_X_ROW = 10044;
const int DIS_UPPER = 10045;
const int DIS_LOWER = 10046;
const int CHECK_Y_ROW = 10047;
const int DIS_LEFT = 10048;
const int DIS_RIGHT = 10049;
const int CHECK_BOX_SIZE = 10050;
const int BOX_SIZE = 10051;
const int CHECK_PLOT = 10052;
const int PLOT_NB = 10053;
wxSizer *Misc( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_BUTTON_RUN_DEFAULT = 10054;
wxSizer *NB_Run( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_COMPACTION = 10055;
const int ID_CHECKBOX_PURESHEAR = 10056;
const int ID_CHECKBOX_BILATERAL = 10057;
const int ID_BUTTON_EXTRADEFORM = 10058;
const int ID_TEXTCTRL_STEPSIZE = 10059;
const int STEPSIZE_DEFAULT = 10060;
const int ID_CHECKBOX_VISCOSITY_ENABLE = 10061;
const int ID_TEXTCTRL_VISCOSITY = 10062;
const int VISCOSITY_DEFAULT = 10063;
wxSizer *DeformStyle( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_DISSOLUTIONSTRAIN = 10064;
const int ID_CHECKBOX_STYLOLITHEDISSOLUTION = 10065;
const int ID_RADIOBOX_DISSOLUTION_STRESS = 10066;
const int STY_STRESS_DEF = 10067;
const int ID_RADIOBOX_DIS_SHRINK = 10068;
const int STY_SHRINK_DEF = 10069;
const int ID_SPINCTRL_DISSOLUTION_PLOT = 10070;
wxSizer *Dissolution( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_SHRINK_GRAIN = 10071;
const int ID_SPINCTRL_GRAINNB = 10072;
const int SHRINK_NB_DEF = 10073;
const int ID_TEXTCTRL_GRAINSHRINK = 10074;
const int SHRINK_SHRINK_DEF = 10075;
const int ID_CHECKBOX_SHRINK_BOX = 10076;
const int ID_TEXTCTRL_SHRINK_BOX = 10077;
const int SHRINK_BOX_DEF = 10078;
const int ID_TEXTCTRL = 10079;
wxSizer *Shrink( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_STRESS_BOX = 10080;
const int ID_BUTTON_EDIT_STRESS_BOX = 10081;
const int ID_CHECKBOX_STRESS_GRAIN = 10082;
const int ID_SPINCTRL_GRAIN_NB = 10083;
const int ID_CHECKBOX_STRESS_TWO_GRAIN = 10084;
const int ID_TEXT_GRAIN_NBS = 10085;
const int ID_SPINCTRL_GRAIN_ONE = 10086;
const int ID_SPINCTRL_GRAIN_TWO = 10087;
const int ID_CHECKBOX_STATISTIC_SURFACE = 10088;
const int ID_CHECKBOX_XSTRESS = 10089;
const int EDIT_XSTRESS = 10090;
wxSizer *Statistics( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_NAME = 10091;
wxSizer *ChangeName( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int GAUSS_MEAN = 10092;
const int GAUSS_MEAN_DEFAULT = 10093;
const int GAUSS_SIGMA = 10094;
const int GAUSS_SIGMA_DEFAULT = 10095;
wxSizer *GaussParams( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_RADIOBOX_SW_BOTH_EDIT = 10096;
const int SW_BOTH_DEF = 10097;
const int SW_CONST_EDIT = 10098;
const int SW_CONST_DEF = 10099;
wxSizer *SetWallParams( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int WH_Y_MIN = 10100;
const int WH_Y_MIN_DEF = 10101;
const int WH_Y_MAX = 10102;
const int WH_Y_MAX_DEF = 10103;
const int WH_CONST = 10104;
const int WH_CONST_DEF = 10105;
const int WH_VISC = 10106;
const int WH_VISC_DEF = 10107;
const int WH_BREAKSTRENGTH = 10108;
const int WH_BREAK_DEF = 10109;
const int ID_CHECKBOX_2ND_LAYER = 10110;
const int ID_BUTTON_2ND_LAYER = 10111;
wxSizer *WeakenLayer( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int WA_CONST = 10112;
const int WA_CONST_DEF = 10113;
const int WA_VISC = 10114;
const int WA_VISC_DEF = 10115;
const int WA_BREAKSTRENGTH = 10116;
const int WA_BREAK_DEF = 10117;
wxSizer *WeakenAll( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int GB_CONST = 10118;
const int MG_CONST_DEF = 10119;
const int GB_BREAKSTRENGTH = 10120;
const int MG_BREAK_DEF = 10121;
wxSizer *MakeGrainBoundaries( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_EXTRADEFORM = 10122;
const int ID_RADIOBOX_EXTRA_DEFORM = 10123;
const int ID_SPINCTRL_EXTRATIMESTEP = 10124;
const int ID_TEXTCTRL_EXTRASTEPSIZE = 10125;
wxSizer *ExtraSettingsDeformation( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_STRESS_BOX_Y_MIN = 10126;
const int ID_TEXTCTRL_STRESS_BOX_Y_MAX = 10127;
const int ID_TEXTCTRL_STRESS_BOX_X_MIN = 10128;
const int ID_TEXTCTRL_STRESS_BOX_X_MAX = 10129;
wxSizer *EditStatisticStressBox( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHOICE_ELLE_FILE = 10130;
const int ID_CHOICE_ZIP_FILE = 10131;
const int ID_BUTTON_BROWSE_ZIP = 10132;
const int ID_CHECKBOX_SHELL = 10133;
const int ID_CHECKBOX_LOCAL_DIR = 10134;
const int ID_SPINCTRL_SAVE_INTERVAL = 10135;
const int ID_BUTTON_EDITEXISTINGFILE = 10136;
const int ID_BUTTON_CREATENEWFILE = 10137;
const int ID_TEXTCTRL_DESC = 10138;
wxSizer *Main( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_BUTTON_EDIT_SETTINGS = 10139;
const int ID_BUTTON_EDIT_RUNFUNCTIONS = 10140;
const int ID_BUTTON_STATISTICS = 10141;
const int ID_BUTTON_CHANGE_NAME = 10142;
const int ID_BUTTON_LATTICE = 10143;
wxSizer *BasicSettingsExistingFile( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_2ND_LAY_Y_MIN = 10144;
const int AD_Y_MIN_DEFAULT = 10145;
const int ID_TEXTCTRL_2ND_LAY_Y_MAX = 10146;
const int AD_Y_MAX_DEFAULT = 10147;
const int ID_TEXTCTRL_2ND_LAY_CONSTANT = 10148;
const int AD_CONST_DEFAULT = 10149;
const int ID_TEXTCTRL_2ND_LAY_VISCOSITY = 10150;
const int AD_VISC_DEFAULT = 10151;
const int ID_TEXTCTRL_2ND_LAY_BREAK_STRENGTH = 10152;
const int AD_BREAK_DEFAULT = 10153;
wxSizer *WeakenAdditionalLayer( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_LINEAR_MEAN1 = 10154;
const int LIN_MEAN1_DEF = 10155;
const int ID_TEXTCTRL_LINEAR_SIZE1 = 10156;
const int LIN_SIZE1_DEF = 10157;
const int ID_LINE = 10158;
const int ID_TEXTCTRL_LINEAR_MEAN2 = 10159;
const int LIN_MEAN2_DEF = 10160;
const int ID_TEXTCTRL_LINEAR_SIZE2 = 10161;
const int LIN_SIZE2_DEF = 10162;
wxSizer *LinearParams( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_CHECKBOX_GG = 10163;
const int ID_CHECKBOX_MELT = 10164;
wxSizer *ExternalProcesses( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_STRESS_XY_Y_MIN = 10165;
const int ID_TEXTCTRL_STRESS_XY_Y_MAX = 10166;
const int ID_TEXTCTRL_STRESS_XY_X_MIN = 10167;
const int ID_TEXTCTRL_STRESS_XY_X_MAX = 10168;
const int ID_RADIOBOX_XY_YX = 10169;
wxSizer *EditXYStress( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

const int ID_TEXTCTRL_GAS_PERCENT = 10170;
const int ID_CHECKBOX_DIFFUSION = 10171;
const int ID_TEXTCTRL_GAS_POROSITY = 10172;
const int ID_SPINCTRL_GRAIN_AMOUNT = 10173;
const int ID_CHECKBOX_FLUID_FLOW = 10174;
const int ID_TEXTCTRL_GAS_PUMP = 10175;
wxSizer *LatticeGas( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

const int ID_MENU = 10176;
const int ID_MENU_NEWP = 10177;
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

void MyToolBarFunc( wxToolBar *parent );

// Declare bitmap functions

#endif

// End of generated file
