//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: mikestart.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma implementation "mikestart_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "mikestart_wdr.h"


// Euro sign hack of the year
#if wxUSE_UNICODE
    #define __WDR_EURO__ wxT("\u20ac")
#else
    #if defined(__WXMAC__)
        #define __WDR_EURO__ wxT("\xdb")
    #elif defined(__WXMSW__)
        #define __WDR_EURO__ wxT("\x80")
    #else
        #define __WDR_EURO__ wxT("\xa4")
    #endif
#endif

// Implement window functions

wxSizer *BasicSettings( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item4 = new wxBoxSizer( wxVERTICAL );

    wxString strs5[] = 
    {
        wxT("Boudins"), 
        wxT("Fractures"), 
        wxT("Expanding inclusions"), 
        wxT("Shrinkage"), 
        wxT("Grooves"), 
        wxT("Stylolites"), 
        wxT("Phase transition"), 
        wxT("Heat flow"), 
        wxT("Grain growth"), 
        wxT("Diffusion"), 
        wxT("Fluid flow"), 
        wxT("Viscoelastic relax"), 
        wxT("Graingrowth with fracturing")
    };
    wxRadioBox *item5 = new wxRadioBox( parent, ID_RADIOBOX_DEFAULTS, wxT("Choose example/defaults"), wxDefaultPosition, wxDefaultSize, 13, strs5, 2, wxNO_BORDER|wxRA_SPECIFY_COLS );
    item5->SetToolTip( wxT("Choose an example to have some default-values") );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 25 );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item7 = new wxStaticText( parent, ID_TEXT, wxT("Name of process:"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT_NAME, wxT("Boudins"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 0 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item10 = new wxBoxSizer( wxVERTICAL );

    wxButton *item11 = new wxButton( parent, ID_BUTTON_ES, wxT("Edit settings"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->SetToolTip( wxT("Basic settings, called upon initialization") );
    item10->Add( item11, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, ID_BUTTON_ER, wxT("Edit runfunctions"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->SetToolTip( wxT("Functions called during every deformation step") );
    item10->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item13 = new wxButton( parent, ID_BUTTON_SS, wxT("Statistics"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->SetToolTip( wxT("Create files containing statistical output") );
    item10->Add( item13, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item9->Add( item10, 0, wxALIGN_CENTER, 20 );

    wxBoxSizer *item14 = new wxBoxSizer( wxVERTICAL );

    wxButton *item15 = new wxButton( parent, ID_BUTTON_EXTERNAL_PROCESSES, wxT("External processes"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->SetToolTip( wxT("Links Latte to other processes") );
    item14->Add( item15, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item16 = new wxButton( parent, ID_BUTTON_NC, wxT("Choose name"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->SetToolTip( wxT("Choose a specific name") );
    item14->Add( item16, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item17 = new wxButton( parent, ID_BUTTON_LATTICE_GAS, wxT("Lattice gas"), wxDefaultPosition, wxSize(75,-1), 0 );
    item14->Add( item17, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item9->Add( item14, 0, wxALIGN_CENTER, 5 );

    item3->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item19 = new wxButton( parent, wxID_OK, wxT("Save / OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->SetDefault();
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item18, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Edit_Settings( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxNotebook *item2 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxDefaultSize, wxNB_BOTTOM );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item1 = new wxNotebookSizer( item2 );
#else
    wxWindow *item1 = item2;
#endif

    wxPanel *item3 = new wxPanel( item2, -1 );
    item2->AddPage( item3, wxT("Distribution") );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Distribution( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item5 = new wxStaticBox( parent, -1, wxT("Breaking strength") );
    wxStaticBoxSizer *item4 = new wxStaticBoxSizer( item5, wxVERTICAL );

    wxString strs6[] = 
    {
        wxT("None"), 
        wxT("Linear"), 
        wxT("Gauss")
    };
    wxRadioBox *item6 = new wxRadioBox( parent, STRENGTH_DISTRI, wxT(""), wxDefaultPosition, wxDefaultSize, 3, strs6, 1, wxNO_BORDER|wxRA_SPECIFY_COLS );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item7 = new wxButton( parent, GSP, wxT("Parameters"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->SetToolTip( wxT("Sets mean and standard deviation") );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item10 = new wxStaticBox( parent, -1, wxT("Gaussian rate") );
    wxStaticBoxSizer *item9 = new wxStaticBoxSizer( item10, wxHORIZONTAL );

    wxCheckBox *item11 = new wxCheckBox( parent, RATE_DISTRI, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item11->SetToolTip( wxT("Sets a gaussian distribution on reaction-rates") );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, GRP, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item14 = new wxStaticBox( parent, -1, wxT("Gaussian Young for grains") );
    wxStaticBoxSizer *item13 = new wxStaticBoxSizer( item14, wxHORIZONTAL );

    wxCheckBox *item15 = new wxCheckBox( parent, SPRING_DISTRI, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item15->SetToolTip( wxT("Sets gaussian distribution on Young's moduli of grains") );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item16 = new wxButton( parent, GSpP, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item18 = new wxStaticBox( parent, -1, wxT("Gaussian Young for particles") );
    wxStaticBoxSizer *item17 = new wxStaticBoxSizer( item18, wxHORIZONTAL );

    wxCheckBox *item19 = new wxCheckBox( parent, YOUNG_DISTRI, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item19->SetToolTip( wxT("Sets gaussian distribution on Young's moduli of particles") );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, EDIT_GAUSSIAN_YOUNG, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Var_Edit_Set( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item5 = new wxStaticBox( parent, -1, wxT("Reaction time per step (in s)") );
    wxStaticBoxSizer *item4 = new wxStaticBoxSizer( item5, wxHORIZONTAL );

    wxCheckBox *item6 = new wxCheckBox( parent, CHECK_TIMESTEP, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, TIMESTEP, wxT("1e9"), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, TS_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item10 = new wxStaticBox( parent, -1, wxT("Mult. relax. thresh") );
    wxStaticBoxSizer *item9 = new wxStaticBoxSizer( item10, wxHORIZONTAL );

    wxCheckBox *item11 = new wxCheckBox( parent, CHECK_MULT_RELAX, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, MULT_RELAX, wxT("1"), wxDefaultPosition, wxSize(80,-1), 0 );
    item12->SetToolTip( wxT("Multiply the relaxation threshold with this number - affects the computation time and the accuracy of the elastic relaxation") );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item13 = new wxButton( parent, RT_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *NB_Set( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxNotebook *item3 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxSize(360,270), 0 );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item2 = new wxNotebookSizer( item3 );
#else
    wxWindow *item2 = item3;
#endif

    wxPanel *item4 = new wxPanel( item3, -1 );
    Distribution( item4, FALSE );
    item3->AddPage( item4, wxT("Distribution") );

    wxPanel *item5 = new wxPanel( item3, -1 );
    Var_Edit_Set( item5, FALSE );
    item3->AddPage( item5, wxT("Variables") );

    wxPanel *item6 = new wxPanel( item3, -1 );
    Lattice( item6, FALSE );
    item3->AddPage( item6, wxT("Lattice") );

    wxPanel *item7 = new wxPanel( item3, -1 );
    Minerals( item7, FALSE );
    item3->AddPage( item7, wxT("Mineral") );

    wxPanel *item8 = new wxPanel( item3, -1 );
    Misc( item8, FALSE );
    item3->AddPage( item8, wxT("Misc") );

    item1->Add( item2, 0, wxADJUST_MINSIZE|wxFIXED_MINSIZE|wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item10 = new wxButton( parent, ID_BUTTON_SET_DEFAULT, wxT("Default"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( 72, 0, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item11 = new wxButton( parent, wxID_OK, wxT("Save / OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->SetDefault();
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_CENTER, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Lattice( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item3 = new wxCheckBox( parent, CHECK_SET_WALLS, wxT("Set Walls"), wxDefaultPosition, wxSize(175,-1), 0 );
    item2->Add( item3, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, EDIT_WALLS, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item4, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item1->Add( item2, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item6 = new wxCheckBox( parent, CHECK_WEAKEN_HORIZ, wxT("Weaken horizontal layer"), wxDefaultPosition, wxSize(175,-1), 0 );
    item6->SetToolTip( wxT("Weakens or strengthens one or two distinct layer") );
    item5->Add( item6, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxButton *item7 = new wxButton( parent, WEAKEN_HORIZ, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item7, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item1->Add( item5, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item9 = new wxCheckBox( parent, CHECK_WEAKEN_ALL, wxT("Weaken all"), wxDefaultPosition, wxSize(175,-1), 0 );
    item9->SetToolTip( wxT("Weakens or strengthens the whole system") );
    item8->Add( item9, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, WEAKEN_ALL, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item1->Add( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item13 = new wxCheckBox( parent, ID_CHECKBOX_WEAKEN_GRAIN, wxT("Weaken grain"), wxDefaultPosition, wxSize(175,-1), 0 );
    item13->SetToolTip( wxT("Weakens or strengthens a single grain") );
    item12->Add( item13, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxTOP, 5 );

    wxButton *item14 = new wxButton( parent, ID_BUTTON_WEAKEN_GRAIN, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxTOP, 5 );

    item11->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Choose grain-nb"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    wxSpinCtrl *item17 = new wxSpinCtrl( parent, ID_SPINCTRL_WEAKEN_GRAIN, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item11->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item19 = new wxCheckBox( parent, CHECK_MAKE_GB, wxT("Make grainboundaries"), wxDefaultPosition, wxSize(175,-1), 0 );
    item19->SetToolTip( wxT("Changes breaking strength or spring constant of grain-boundaries") );
    item18->Add( item19, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, EDIT_GB, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item11->Add( item18, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item0->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Minerals( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxString strs3[] = 
    {
        wxT("None"), 
        wxT("Quartz"), 
        wxT("NaCl"), 
        wxT("Olivine")
    };
    wxRadioBox *item3 = new wxRadioBox( parent, ID_MINERAL, wxT("Choose mineral"), wxDefaultPosition, wxDefaultSize, 4, strs3, 2, wxRA_SPECIFY_COLS );
    item3->SetToolTip( wxT("sets parameters as molare volume, density etc to a certain mineral") );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item5 = new wxStaticBox( parent, -1, wxT("Phase transition") );
    wxStaticBoxSizer *item4 = new wxStaticBoxSizer( item5, wxVERTICAL );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item7 = new wxCheckBox( parent, ID_CHECKBOX_TRANSITION, wxT("Ol->spin transition"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->SetToolTip( wxT("Simulates olivine->spinel transition (without nucleation and fracturing)") );
    item6->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    item8->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxCheckBox *item9 = new wxCheckBox( parent, ID_CHECKBOX_TRANSITION_HEAT, wxT("include heat-conduction"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->SetToolTip( wxT("Includes the latent-heat release into the transition") );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    item10->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, wxT("Activation energy:"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_TEXTCTRL_ACTIVATION_ENERGY, wxT("400000"), wxDefaultPosition, wxSize(80,-1), 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT, wxT("Joule"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    item14->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item15 = new wxStaticText( parent, ID_TEXT, wxT("Start the reaction at"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item16 = new wxTextCtrl( parent, ID_TEXTCTRL_START_GPA, wxT("12"), wxDefaultPosition, wxSize(80,-1), 0 );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item17 = new wxStaticText( parent, ID_TEXT, wxT("GPa"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 10 );

    wxCheckBox *item18 = new wxCheckBox( parent, ID_CHECKBOX_HEAT_CONDUCTION, wxT("Heat-conduction example (uses timestep and absolute box-size):"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->SetToolTip( wxT("ONLY usable as an example(!): uses olivine-parameters: density 4.2, capacity 1005, diffusivity 0.000001, boundary condition / matrix = 1000 °K. Preheat a grain to a certain temperature and see what happens...") );
    item0->Add( item18, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxTOP, 15 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Grain nb:"), wxDefaultPosition, wxDefaultSize, 0 );
    item20->SetToolTip( wxT("choose temperature for a particular grain") );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item21 = new wxSpinCtrl( parent, ID_SPINCTRL_HEAT_CONDUCTION_NB, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item21->SetToolTip( wxT("choose temperature for a particular grain") );
    item19->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item22 = new wxStaticText( parent, ID_TEXT, wxT("T (°K)"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->SetToolTip( wxT("choose temperature for a particular grain") );
    item19->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item23 = new wxSpinCtrl( parent, ID_SPINCTRL_HEAT_CONDUCTION_T, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 500, 2000, 0 );
    item23->SetToolTip( wxT("choose temperature for a particular grain") );
    item19->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item19, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Misc( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("Dissolve x-rows") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item5 = new wxCheckBox( parent, CHECK_X_ROW, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item5->SetToolTip( wxT("Dissolves all particles between limits") );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("upper limit"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, DIS_UPPER, wxT("0"), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item7, 0, wxGROW|wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item2->Add( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("lower limit"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item10 = new wxTextCtrl( parent, DIS_LOWER, wxT("0"), wxDefaultPosition, wxSize(80,-1), 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item12 = new wxStaticBox( parent, -1, wxT("Dissolve y-rows") );
    wxStaticBoxSizer *item11 = new wxStaticBoxSizer( item12, wxVERTICAL );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item14 = new wxCheckBox( parent, CHECK_Y_ROW, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item14->SetToolTip( wxT("Dissolves all particles between limits") );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item15 = new wxStaticText( parent, ID_TEXT, wxT("left limit"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item16 = new wxTextCtrl( parent, DIS_LEFT, wxT("0"), wxDefaultPosition, wxSize(80,-1), 0 );
    item13->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    item11->Add( item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("right limit"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, DIS_RIGHT, wxT("0"), wxDefaultPosition, wxSize(80,-1), 0 );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    item11->Add( item17, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item20 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item21 = new wxCheckBox( parent, CHECK_BOX_SIZE, wxT("Set box-size? (m)"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->SetToolTip( wxT("Sets the system-size for e.g. reactions") );
    item20->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item22 = new wxTextCtrl( parent, BOX_SIZE, wxT("0,001"), wxDefaultPosition, wxSize(80,-1), 0 );
    item20->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item23 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item24 = new wxCheckBox( parent, CHECK_PLOT, wxT("Plot after cert. nb. of fractures?"), wxDefaultPosition, wxDefaultSize, 0 );
    item24->SetToolTip( wxT("Save an elle-file, even if the deformation-step is not completed") );
    item23->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item25 = new wxSpinCtrl( parent, PLOT_NB, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item23->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *NB_Run( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxNotebook *item3 = new wxNotebook( parent, ID_NOTEBOOK, wxDefaultPosition, wxSize(360,270), 0 );
#if !wxCHECK_VERSION(2,5,2)
    wxNotebookSizer *item2 = new wxNotebookSizer( item3 );
#else
    wxWindow *item2 = item3;
#endif

    wxPanel *item4 = new wxPanel( item3, -1 );
    DeformStyle( item4, FALSE );
    item3->AddPage( item4, wxT("Deformation style") );

    wxPanel *item5 = new wxPanel( item3, -1 );
    Dissolution( item5, FALSE );
    item3->AddPage( item5, wxT("Dissolution") );

    wxPanel *item6 = new wxPanel( item3, -1 );
    Shrink( item6, FALSE );
    item3->AddPage( item6, wxT("Shrink") );

    item1->Add( item2, 0, wxADJUST_MINSIZE|wxFIXED_MINSIZE|wxALIGN_CENTER|wxALL, 0 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item8 = new wxButton( parent, ID_BUTTON_RUN_DEFAULT, wxT("Default"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item7->Add( 72, 0, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("Save / OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->SetDefault();
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item7, 0, wxALIGN_CENTER, 0 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *DeformStyle( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item4 = new wxStaticBox( parent, -1, wxT("Deformation type") );
    wxStaticBoxSizer *item3 = new wxStaticBoxSizer( item4, wxVERTICAL );

    wxCheckBox *item5 = new wxCheckBox( parent, ID_CHECKBOX_COMPACTION, wxT("Compaction"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->SetToolTip( wxT("Moves top down") );
    item3->Add( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item6 = new wxCheckBox( parent, ID_CHECKBOX_PURESHEAR, wxT("Pure shear"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->SetToolTip( wxT("Top down and right boundary-extension") );
    item3->Add( item6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item7 = new wxCheckBox( parent, ID_CHECKBOX_BILATERAL, wxT("Bilateral compaction"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->SetToolTip( wxT("Compaction from top and bottom") );
    item3->Add( item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, ID_BUTTON_EXTRADEFORM, wxT("Extra Settings"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->SetToolTip( wxT("Adds an additional deformation-style, which will be executed instead of the one above for a defined time") );
    item3->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item11 = new wxStaticBox( parent, -1, wxT("Vertical strain per step") );
    wxStaticBoxSizer *item10 = new wxStaticBoxSizer( item11, wxHORIZONTAL );

    item10->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_TEXTCTRL_STEPSIZE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item13 = new wxButton( parent, STEPSIZE_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item15 = new wxStaticBox( parent, -1, wxT("Viscosity") );
    wxStaticBoxSizer *item14 = new wxStaticBoxSizer( item15, wxHORIZONTAL );

    wxCheckBox *item16 = new wxCheckBox( parent, ID_CHECKBOX_VISCOSITY_ENABLE, wxT("Time for viscous relaxation:"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item17 = new wxTextCtrl( parent, ID_TEXTCTRL_VISCOSITY, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item17->SetToolTip( wxT("Scales the newtonian viscosity function.") );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item18 = new wxButton( parent, VISCOSITY_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Dissolution( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item4 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item3 = new wxStaticBoxSizer( item4, wxVERTICAL );

    wxCheckBox *item5 = new wxCheckBox( parent, ID_CHECKBOX_DISSOLUTIONSTRAIN, wxT("Dissolution strain"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->SetToolTip( wxT("Dissolution as function of elastic and surface energies, dissolution of quartz in 200° water") );
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item7 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item6 = new wxStaticBoxSizer( item7, wxVERTICAL );

    wxCheckBox *item8 = new wxCheckBox( parent, ID_CHECKBOX_STYLOLITHEDISSOLUTION, wxT("Stylolithe dissolution"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs10[] = 
    {
        wxT("Normal stress + energy"), 
        wxT("Normal stress only")
    };
    wxRadioBox *item10 = new wxRadioBox( parent, ID_RADIOBOX_DISSOLUTION_STRESS, wxT("Stress"), wxDefaultPosition, wxDefaultSize, 2, strs10, 1, wxRA_SPECIFY_ROWS );
    item10->SetToolTip( wxT("Use either surface + elastic energy + normal stress or solely normal stress") );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item11 = new wxButton( parent, STY_STRESS_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item6->Add( item9, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs13[] = 
    {
        wxT("Dissolve one particle at a time"), 
        wxT("Shrink all particles")
    };
    wxRadioBox *item13 = new wxRadioBox( parent, ID_RADIOBOX_DIS_SHRINK, wxT("Shrink"), wxDefaultPosition, wxDefaultSize, 2, strs13, 1, wxRA_SPECIFY_ROWS );
    item13->SetToolTip( wxT("Dissolve particles one-by-one or use time of fastest particle to shrink others") );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item14 = new wxButton( parent, STY_SHRINK_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item6->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALL, 5 );

    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Plot picture after N particles have been dissolved:"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item17 = new wxSpinCtrl( parent, ID_SPINCTRL_DISSOLUTION_PLOT, wxT("1"), wxDefaultPosition, wxSize(100,-1), 0, 1, 1000, 1 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Shrink( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item4 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item3 = new wxStaticBoxSizer( item4, wxVERTICAL );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item6 = new wxCheckBox( parent, ID_CHECKBOX_SHRINK_GRAIN, wxT("Shrink grain"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("Grain number"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item9 = new wxSpinCtrl( parent, ID_SPINCTRL_GRAINNB, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, SHRINK_NB_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item7, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("Shrinkage"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_TEXTCTRL_GRAINSHRINK, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item13->SetToolTip( wxT("Shrinkage given by factor, which will is applied on the actual radius, then added. (Values < 0 shrink, > 0 increase)") );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item14 = new wxButton( parent, SHRINK_SHRINK_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item3->Add( item11, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item16 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item15 = new wxStaticBoxSizer( item16, wxVERTICAL );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item18 = new wxCheckBox( parent, ID_CHECKBOX_SHRINK_BOX, wxT("Shrink box"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item15->Add( item17, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item19 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Shrinkage"), wxDefaultPosition, wxDefaultSize, 0 );
    item19->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, ID_TEXTCTRL_SHRINK_BOX, wxT("0.0"), wxDefaultPosition, wxSize(80,-1), 0 );
    item21->SetToolTip( 
        wxT("Shrinkage given by factor (1.0 is no change,\n")
        wxT(" larger 1.0 is growth and smaller shrinking)")  );
    item19->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    item15->Add( item19, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item22 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item23 = new wxButton( parent, SHRINK_BOX_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item15->Add( item22, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item2->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALL, 5 );

    wxStaticBox *item25 = new wxStaticBox( parent, -1, wxT("Set a sinoidal anisotropy:") );
    wxStaticBoxSizer *item24 = new wxStaticBoxSizer( item25, wxHORIZONTAL );

    wxBoxSizer *item26 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item27 = new wxStaticText( parent, ID_TEXT, wxT("Wavelength"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item28 = new wxTextCtrl( parent, ID_TEXTCTRL, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item28->SetToolTip( wxT("Controls the number of waves") );
    item26->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );

    item24->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item29 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item30 = new wxStaticText( parent, ID_TEXT, wxT("Amplitude (0.1 ... 2.1)"), wxDefaultPosition, wxDefaultSize, 0 );
    item29->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item31 = new wxTextCtrl( parent, ID_TEXTCTRL, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item31->SetToolTip( wxT("Uses 0.1 ... 2.1 instead of -1 ... 1 to avoid 0") );
    item29->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );

    item24->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Statistics( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item4 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item3 = new wxStaticBoxSizer( item4, wxVERTICAL );

    wxCheckBox *item5 = new wxCheckBox( parent, ID_CHECKBOX_STRESS_BOX, wxT("Statistic stress of box"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->SetToolTip( 
        wxT("Calculates means for mean stress, \n")
        wxT(" differential stress and stress tensor (sxx, syy, sxy) in a box")  );
    item3->Add( item5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item7 = new wxButton( parent, ID_BUTTON_EDIT_STRESS_BOX, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item7, 0, wxALIGN_CENTER_VERTICAL|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item3, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticBox *item9 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item8 = new wxStaticBoxSizer( item9, wxVERTICAL );

    wxCheckBox *item10 = new wxCheckBox( parent, ID_CHECKBOX_STRESS_GRAIN, wxT("Statistic stress of grain"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->SetToolTip( 
        wxT("Dumps strain, mean stress, smax, sxx, syy, sxy and differential stress\n")
        wxT("")  );
    item8->Add( item10, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("grain-nb:"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item13 = new wxSpinCtrl( parent, ID_SPINCTRL_GRAIN_NB, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item11, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item2->Add( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticBox *item15 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item14 = new wxStaticBoxSizer( item15, wxVERTICAL );

    wxCheckBox *item16 = new wxCheckBox( parent, ID_CHECKBOX_STRESS_TWO_GRAIN, wxT("Statistic stress of two grains"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->SetToolTip( 
        wxT("Dumps strain, mean stress, smax, sxx, syy, sxy and differential stress\n")
        wxT("")  );
    item14->Add( item16, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT_GRAIN_NBS, wxT("grain-nbs:"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item19 = new wxSpinCtrl( parent, ID_SPINCTRL_GRAIN_ONE, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item20 = new wxSpinCtrl( parent, ID_SPINCTRL_GRAIN_TWO, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item17->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item14->Add( item17, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item2->Add( item14, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticBox *item22 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item21 = new wxStaticBoxSizer( item22, wxHORIZONTAL );

    wxCheckBox *item23 = new wxCheckBox( parent, ID_CHECKBOX_STATISTIC_SURFACE, wxT("Statistic surface"), wxDefaultPosition, wxDefaultSize, 0 );
    item23->SetToolTip( wxT("Plots x-y coordinates of surface particles and the strain") );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item21, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticBox *item25 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item24 = new wxStaticBoxSizer( item25, wxVERTICAL );

    wxCheckBox *item26 = new wxCheckBox( parent, ID_CHECKBOX_XSTRESS, wxT("x-stress"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->SetToolTip( 
        wxT("Dumps the stress tensor, x or y position of particle,\n")
        wxT(" the mean stress, differential stress and elastic energy\n")
        wxT(" within a box")  );
    item24->Add( item26, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item27 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item28 = new wxButton( parent, EDIT_XSTRESS, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item27->Add( item28, 0, wxALIGN_CENTER_VERTICAL|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item24->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item24, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item2, 0, wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item29 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item30 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item29->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item31 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item29->Add( item31, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item29, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *ChangeName( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Enter a new name for the process"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_TEXTCTRL_NAME, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item5 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *GaussParams( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("mean:"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, GAUSS_MEAN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, GAUSS_MEAN_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("sigma:"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, GAUSS_SIGMA, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, GAUSS_SIGMA_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->SetDefault();
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *SetWallParams( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs2[] = 
    {
        wxT("Wall only"), 
        wxT("Apply on wall AND boundary particles")
    };
    wxRadioBox *item2 = new wxRadioBox( parent, ID_RADIOBOX_SW_BOTH_EDIT, wxT("Both"), wxDefaultPosition, wxDefaultSize, 2, strs2, 1, wxRA_SPECIFY_ROWS );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item3 = new wxButton( parent, SW_BOTH_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("const"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, SW_CONST_EDIT, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item6->SetToolTip( wxT("Multiplies current Young's modulus with this number") );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item7 = new wxButton( parent, SW_CONST_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item4, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *WeakenLayer( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("y min (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, WH_Y_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Lower boundary of horizontal layer, 0 = bottom, 1 = top") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, WH_Y_MIN_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("y max (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, WH_Y_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->SetToolTip( wxT("Upper boundary of horizontal layer, 0 = bottom, 1 = top") );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, WH_Y_MAX_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("constant"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, WH_CONST, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item11->SetToolTip( wxT("Changes spring constant by a factor, 1 = no change") );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, WH_CONST_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("viscosity"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item15 = new wxTextCtrl( parent, WH_VISC, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item15->SetToolTip( wxT("Changes viscosity by a factor, 1 = no change") );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item16 = new wxButton( parent, WH_VISC_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("break. strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, WH_BREAKSTRENGTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item19->SetToolTip( wxT("Changes breaking strength by a factor, 1 = no change") );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, WH_BREAK_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item17, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticBox *item22 = new wxStaticBox( parent, -1, wxT("Weaken 2nd layer") );
    wxStaticBoxSizer *item21 = new wxStaticBoxSizer( item22, wxHORIZONTAL );

    wxCheckBox *item23 = new wxCheckBox( parent, ID_CHECKBOX_2ND_LAYER, wxT(""), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 10 );

    wxButton *item24 = new wxButton( parent, ID_BUTTON_2ND_LAYER, wxT("Edit"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item24, 0, wxALIGN_CENTER|wxALL, 10 );

    item0->Add( item21, 0, wxALIGN_CENTER_VERTICAL|wxLEFT, 10 );

    wxBoxSizer *item25 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item26 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item27 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item25, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 10 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *WeakenAll( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("constant"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, WA_CONST, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Changes spring constant by a factor, 1 = no change") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, WA_CONST_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("viscosity"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, WA_VISC, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->SetToolTip( wxT("Changes viscosity by a factor, 1 = no change") );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, WA_VISC_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("break. strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, WA_BREAKSTRENGTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item11->SetToolTip( wxT("Changes breaking strength by a factor, 1 = no change") );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, WA_BREAK_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item14 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item15 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *MakeGrainBoundaries( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("constant"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, GB_CONST, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Changes spring constant by a factor, 1 = no change") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, MG_CONST_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("break. strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, GB_BREAKSTRENGTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->SetToolTip( wxT("Changes breaking strength by a factor, 1 = no change") );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, MG_BREAK_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item10 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item11 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *ExtraSettingsDeformation( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Before applying the selected deformation-type, apply"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxCheckBox *item5 = new wxCheckBox( parent, ID_CHECKBOX_EXTRADEFORM, wxT("one of the following:"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs7[] = 
    {
        wxT("Compaction"), 
        wxT("Pure shear"), 
        wxT("Bilateral compaction")
    };
    wxRadioBox *item7 = new wxRadioBox( parent, ID_RADIOBOX_EXTRA_DEFORM, wxT("Deformation types"), wxDefaultPosition, wxDefaultSize, 3, strs7, 1, wxRA_SPECIFY_COLS );
    item6->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("until timestep"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item10 = new wxSpinCtrl( parent, ID_SPINCTRL_EXTRATIMESTEP, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item8, 0, wxALIGN_CENTER_VERTICAL|wxRIGHT|wxTOP|wxBOTTOM, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("with stepsize"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_TEXTCTRL_EXTRASTEPSIZE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item15 = new wxStaticText( parent, ID_TEXT, wxT("then continue with the main deformation-type"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item17 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item18 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item16, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item0->Add( item1, 0, wxALL, 15 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *EditStatisticStressBox( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("y min (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_BOX_Y_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Defines a box, 0.0 = bottom/left boundary, 1.0 = top/right boundary") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("y max (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item6 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_BOX_Y_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item4->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item8 = new wxStaticText( parent, ID_TEXT, wxT("x min (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item9 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_BOX_X_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, wxT("x max (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_BOX_X_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item14 = new wxBoxSizer( wxVERTICAL );

    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item15 = new wxBoxSizer( wxVERTICAL );

    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item16 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item17 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item18 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item16->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *Main( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("File") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item5 = new wxStaticText( parent, ID_TEXT, wxT("Choose an elle-file"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->Add( item5, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxTOP, 5 );

    item2->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item6 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs7[] = 
    {
        wxT("None selected")
    };
    wxChoice *item7 = new wxChoice( parent, ID_CHOICE_ELLE_FILE, wxDefaultPosition, wxSize(216,-1), 1, strs7, 0 );
    item6->Add( item7, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item2->Add( item6, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("Import prefs from different archive"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxTOP, 5 );

    item2->Add( item8, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    wxString strs11[] = 
    {
        wxT("None selected")
    };
    wxChoice *item11 = new wxChoice( parent, ID_CHOICE_ZIP_FILE, wxDefaultPosition, wxSize(216,-1), 1, strs11, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    wxButton *item12 = new wxButton( parent, ID_BUTTON_BROWSE_ZIP, wxT("Browse"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item12, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item2->Add( item10, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item13 = new wxCheckBox( parent, ID_CHECKBOX_SHELL, wxT("Run in a shell (*nix only)"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item13, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxCheckBox *item14 = new wxCheckBox( parent, ID_CHECKBOX_LOCAL_DIR, wxT("Start lattex from local directory"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->SetToolTip( wxT("Calling latte globally assumes, that it (or elle) is included in your PATH-variable") );
    item2->Add( item14, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item15 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Save-interval:"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item16, 0, wxALIGN_CENTER|wxLEFT|wxTOP|wxBOTTOM, 5 );

    wxSpinCtrl *item17 = new wxSpinCtrl( parent, ID_SPINCTRL_SAVE_INTERVAL, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 100, 0 );
    item15->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item2->Add( item15, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item20 = new wxStaticBox( parent, -1, wxT("Edit") );
    wxStaticBoxSizer *item19 = new wxStaticBoxSizer( item20, wxHORIZONTAL );

    wxButton *item21 = new wxButton( parent, ID_BUTTON_EDITEXISTINGFILE, wxT("Edit existing pref-file"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->SetToolTip( wxT("This will edit an already existing pref-file") );
    item19->Add( item21, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxButton *item22 = new wxButton( parent, ID_BUTTON_CREATENEWFILE, wxT("Create new pref-file"), wxDefaultPosition, wxDefaultSize, 0 );
    item22->SetToolTip( wxT("This gives you the option to choose reasonable default-values or to start examples") );
    item19->Add( item22, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item23 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item24 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item25 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item26 = new wxStaticText( parent, ID_TEXT, wxT("Description:"), wxDefaultPosition, wxDefaultSize, 0 );
    item25->Add( item26, 0, wxLEFT|wxRIGHT|wxTOP, 5 );

    wxTextCtrl *item27 = new wxTextCtrl( parent, ID_TEXTCTRL_DESC, wxT(""), wxDefaultPosition, wxSize(253,70), wxTE_MULTILINE );
    item25->Add( item27, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT|wxBOTTOM, 5 );

    item24->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    item23->Add( item24, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item28 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item29 = new wxButton( parent, wxID_OK, wxT("Start run"), wxDefaultPosition, wxDefaultSize, 0 );
    item29->SetDefault();
    item29->SetToolTip( wxT("Starts a process from the pref-file") );
    item28->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item30 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item28->Add( item30, 0, wxALIGN_CENTER|wxALL, 5 );

    item23->Add( item28, 0, wxALIGN_CENTER|wxALL, 5 );

    item18->Add( item23, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *BasicSettingsExistingFile( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item2 = new wxStaticBox( parent, -1, wxT("Settings") );
    wxStaticBoxSizer *item1 = new wxStaticBoxSizer( item2, wxVERTICAL );

    wxBoxSizer *item3 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item4 = new wxButton( parent, ID_BUTTON_EDIT_SETTINGS, wxT("Edit settings"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->SetToolTip( wxT("Basic settings, called upon initialization") );
    item3->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item5 = new wxButton( parent, ID_BUTTON_EDIT_RUNFUNCTIONS, wxT("Edit runfunctions"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->SetToolTip( wxT("Functions called during every deformation step") );
    item3->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, ID_BUTTON_EXTERNAL_PROCESSES, wxT("External processes"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->SetToolTip( wxT("Links Latte to other processes") );
    item3->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item7 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item8 = new wxButton( parent, ID_BUTTON_STATISTICS, wxT("Edit statistic functions"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->SetToolTip( wxT("Create files containing statistical output") );
    item7->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item9 = new wxButton( parent, ID_BUTTON_CHANGE_NAME, wxT("Change name"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->SetToolTip( wxT("Choose a name for the current settings") );
    item7->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, ID_BUTTON_LATTICE, wxT("Lattice gas"), wxDefaultPosition, wxDefaultSize, 0 );
    item7->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("Current name:"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT_NAME, wxT("text"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item11, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item15 = new wxStaticBox( parent, -1, wxT("Exit") );
    wxStaticBoxSizer *item14 = new wxStaticBoxSizer( item15, wxVERTICAL );

    wxButton *item16 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item17 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *WeakenAdditionalLayer( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("y min (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_TEXTCTRL_2ND_LAY_Y_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Lower boundary of horizontal layer, 0 = bottom, 1 = top") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, AD_Y_MIN_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("y max (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_TEXTCTRL_2ND_LAY_Y_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->SetToolTip( wxT("Upper boundary of horizontal layer, 0 = bottom, 1 = top") );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, AD_Y_MAX_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("constant"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, ID_TEXTCTRL_2ND_LAY_CONSTANT, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item11->SetToolTip( wxT("Changes spring constant by a factor, 1 = no change") );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item12 = new wxButton( parent, AD_CONST_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item9, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item13 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("viscosity"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item15 = new wxTextCtrl( parent, ID_TEXTCTRL_2ND_LAY_VISCOSITY, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item15->SetToolTip( wxT("Changes viscosity by a factor, 1 = no change") );
    item13->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item16 = new wxButton( parent, AD_VISC_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item13->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item13, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("break. strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, ID_TEXTCTRL_2ND_LAY_BREAK_STRENGTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item19->SetToolTip( wxT("Changes breaking strength by a factor, 1 = no change") );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, AD_BREAK_DEFAULT, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item17, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item22 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item23 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item21, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *LinearParams( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("mean for spring constants"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_TEXTCTRL_LINEAR_MEAN1, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item3->SetToolTip( wxT("Applied on grains, sets mean for spring constants") );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item4 = new wxButton( parent, LIN_MEAN1_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("range for springconstants"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_TEXTCTRL_LINEAR_SIZE1, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item7->SetToolTip( wxT("mean * (springconstant +/- (springconstant * (range/2)))") );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item8 = new wxButton( parent, LIN_SIZE1_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxStaticLine *item9 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(132,-1), 0 );
    item0->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item10 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item11 = new wxStaticText( parent, ID_TEXT, wxT("mean for breaking strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item12 = new wxTextCtrl( parent, ID_TEXTCTRL_LINEAR_MEAN2, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item12->SetToolTip( wxT("Applied on whole model, sets mean for breaking strength") );
    item10->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item13 = new wxButton( parent, LIN_MEAN2_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item10->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item10, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item15 = new wxStaticText( parent, ID_TEXT, wxT("range for breaking strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item16 = new wxTextCtrl( parent, ID_TEXTCTRL_LINEAR_SIZE2, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item16->SetToolTip( wxT("mean * (breakingstrength +/- (breakingstrength * (range/2)))") );
    item14->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item17 = new wxButton( parent, LIN_SIZE2_DEF, wxT("Reset"), wxDefaultPosition, wxDefaultSize, 0 );
    item14->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item14, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item19 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item20 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item18, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *ExternalProcesses( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item3 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item2 = new wxStaticBoxSizer( item3, wxVERTICAL );

    wxCheckBox *item4 = new wxCheckBox( parent, ID_CHECKBOX_GG, wxT("Graingrowth"), wxDefaultPosition, wxDefaultSize, 0 );
    item4->SetToolTip( wxT("Links Latte to the external Graingrowth-process") );
    item2->Add( item4, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 15 );

    wxStaticBox *item6 = new wxStaticBox( parent, -1, wxT("") );
    wxStaticBoxSizer *item5 = new wxStaticBoxSizer( item6, wxVERTICAL );

    wxCheckBox *item7 = new wxCheckBox( parent, ID_CHECKBOX_MELT, wxT("Elle-melt"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item7, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item1->Add( item5, 0, wxALIGN_CENTER|wxALL, 15 );

    item0->Add( item1, 0, wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item9 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item10 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *EditXYStress( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item2 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("y min (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item4 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_XY_Y_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item2, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item5 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item6 = new wxStaticText( parent, ID_TEXT, wxT("y max  (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item7 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_XY_Y_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item5->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item5, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item9 = new wxStaticText( parent, ID_TEXT, wxT("x min  (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item8->Add( item9, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item10 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_XY_X_MIN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item8->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item8, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item11 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("x max  (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_TEXTCTRL_STRESS_XY_X_MAX, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item11, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item14 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item15 = new wxBoxSizer( wxVERTICAL );

    wxString strs16[] = 
    {
        wxT("Y coordinates"), 
        wxT("X coordinates")
    };
    wxRadioBox *item16 = new wxRadioBox( parent, ID_RADIOBOX_XY_YX, wxT("Plot:"), wxDefaultPosition, wxDefaultSize, 2, strs16, 1, wxRA_SPECIFY_ROWS );
    item15->Add( item16, 0, wxALIGN_CENTER|wxALL, 5 );

    item14->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item17 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item18 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item18, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item19 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item17->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    item1->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

wxSizer *LatticeGas( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxBoxSizer *item1 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item2 = new wxStaticText( parent, ID_TEXT, wxT("Fluid density in percent (0.0 ... 1.0)"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item3 = new wxTextCtrl( parent, ID_TEXTCTRL_GAS_PERCENT, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item1->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item1, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item4 = new wxBoxSizer( wxHORIZONTAL );

    wxBoxSizer *item5 = new wxBoxSizer( wxVERTICAL );

    wxStaticBox *item7 = new wxStaticBox( parent, -1, wxT("Diffusion") );
    wxStaticBoxSizer *item6 = new wxStaticBoxSizer( item7, wxVERTICAL );

    wxCheckBox *item8 = new wxCheckBox( parent, ID_CHECKBOX_DIFFUSION, wxT("Simulate diffusion"), wxDefaultPosition, wxDefaultSize, 0 );
    item6->Add( item8, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item9 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item10 = new wxStaticText( parent, ID_TEXT, wxT("Fluid-density (0.0 ... 1.0):"), wxDefaultPosition, wxDefaultSize, 0 );
    item9->Add( item10, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item11 = new wxTextCtrl( parent, ID_TEXTCTRL_GAS_POROSITY, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item6->Add( item9, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    wxBoxSizer *item12 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item13 = new wxStaticText( parent, ID_TEXT, wxT("Set every nth grain impermeable:"), wxDefaultPosition, wxDefaultSize, 0 );
    item12->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item14 = new wxSpinCtrl( parent, ID_SPINCTRL_GRAIN_AMOUNT, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 15, 0 );
    item12->Add( item14, 0, wxALIGN_CENTER|wxALL, 5 );

    item6->Add( item12, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 0 );

    item5->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    item4->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticBox *item16 = new wxStaticBox( parent, -1, wxT("Fluid flow") );
    wxStaticBoxSizer *item15 = new wxStaticBoxSizer( item16, wxVERTICAL );

    wxCheckBox *item17 = new wxCheckBox( parent, ID_CHECKBOX_FLUID_FLOW, wxT("Particle-flow from left to rigth system-boundary"), wxDefaultPosition, wxDefaultSize, 0 );
    item15->Add( item17, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxBoxSizer *item18 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticText *item19 = new wxStaticText( parent, ID_TEXT, wxT("Background fluid density (0.0 ... 1.0):"), wxDefaultPosition, wxDefaultSize, 0 );
    item18->Add( item19, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item20 = new wxTextCtrl( parent, ID_TEXTCTRL_GAS_PUMP, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item18->Add( item20, 0, wxALIGN_CENTER|wxALL, 5 );

    item15->Add( item18, 0, wxGROW|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    item4->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item4, 0, wxALIGN_CENTER|wxALL, 0 );

    wxBoxSizer *item21 = new wxBoxSizer( wxHORIZONTAL );

    wxButton *item22 = new wxButton( parent, wxID_OK, wxT("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item22, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item23 = new wxButton( parent, wxID_CANCEL, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    item21->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item21, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetSizer( item0 );
        if (call_fit)
            item0->SetSizeHints( parent );
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *MyMenuBarFunc()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( wxID_ABOUT, wxT("About"), wxT("") );
    item1->Append( wxID_EXIT, wxT("Quit"), wxT("") );
    item0->Append( item1, wxT("File") );
    
    wxMenu* item2 = new wxMenu;
    item2->Append( ID_MENU_NEWP, wxT("New pref-file"), wxT("") );
    item0->Append( item2, wxT("Process") );
    
    return item0;
}

// Implement toolbar functions

void MyToolBarFunc( wxToolBar *parent )
{
    parent->SetMargins( 2, 2 );
    
    
    parent->Realize();
}

// Implement bitmap functions


// End of generated file
